// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package ac

import (
	metav1 "github.com/jpbetz/ssademo/ac/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// FooApplyConfiguration represents a declarative configuration of the Foo type for use
// with apply.
type FooApplyConfiguration struct {
	v1.TypeMeta   `json:",inline"`
	v1.ObjectMeta `json:"metadata"`
	Spec          *FooSpecApplyConfiguration   `json:"spec,omitempty"`
	Status        *FooStatusApplyConfiguration `json:"status,omitempty"`
}

// FooApplyConfiguration represents a declarative configuration of the Foo type for use
// with apply.
func Foo() *FooApplyConfiguration {
	return &FooApplyConfiguration{}
}
func (ac *FooApplyConfiguration) DeepCopy() *FooApplyConfiguration {
	return ac
}
func (ac *FooApplyConfiguration) DeepCopyObject() runtime.Object {
	return ac
}
func (ac *FooApplyConfiguration) SetSpec(spec *FooSpecApplyConfiguration) *FooApplyConfiguration {
	ac.Spec = spec
	return ac
}

// FooListApplyConfiguration represents a declarative configuration of the FooList type for use
// with apply.
type FooListApplyConfiguration struct {
	v1.TypeMeta                       `json:",inline"`
	metav1.ListMetaApplyConfiguration `json:"metadata"`
	Items                             *[]FooApplyConfiguration `json:"items,omitempty"`
}

// FooListApplyConfiguration represents a declarative configuration of the FooList type for use
// with apply.
func FooList() *FooListApplyConfiguration {
	return &FooListApplyConfiguration{}
}
func (ac *FooListApplyConfiguration) DeepCopy() *FooListApplyConfiguration {
	return ac
}
func (ac *FooListApplyConfiguration) DeepCopyObject() runtime.Object {
	return ac
}

// FooSpecApplyConfiguration represents a declarative configuration of the FooSpec type for use
// with apply.
type FooSpecApplyConfiguration struct {
	DeploymentName *string `json:"deploymentName,omitempty"`
	Replicas       *int32  `json:"replicas,omitempty"`
}

// FooSpecApplyConfiguration represents a declarative configuration of the FooSpec type for use
// with apply.
func FooSpec() *FooSpecApplyConfiguration {
	return &FooSpecApplyConfiguration{}
}
func (ac *FooSpecApplyConfiguration) SetReplicas(replicas int32) *FooSpecApplyConfiguration {
	ac.Replicas = &replicas
	return ac
}

// FooStatusApplyConfiguration represents a declarative configuration of the FooStatus type for use
// with apply.
type FooStatusApplyConfiguration struct {
	AvailableReplicas *int32 `json:"availableReplicas,omitempty"`
}

// FooStatusApplyConfiguration represents a declarative configuration of the FooStatus type for use
// with apply.
func FooStatus() *FooStatusApplyConfiguration {
	return &FooStatusApplyConfiguration{}
}
